### ISSUE TITLE
demo site/deploy.sh not working

### ISSUE THREAD

**Issue by EugeneEA** [ForomePlatform/anfisa#13]
Hi! I wanted to try out forome but so far failed either to install it locally or launch a demo. Demo site is down and during local installation (deploy.sh) I'm also failing to upload necessary data:

  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed connect to anfisa.forome.dev:443; Connection timed out

Best, Eugene

**Comment by mmcentre** [comment]
The issue should have been solved by now. The demo site is working and the deployment should work both via docker and on a bare metal system.
